# Generated by Django 2.2 on 2019-10-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191013_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Sunglasses'), ('G', 'Prescription'), ('R', 'Recomended')], max_length=2),
        ),
    ]
